import os
import sys

HOOK_DIR = ".git/hooks"
HOOK_FILE = os.path.join(HOOK_DIR, "pre-push")

HOOK_CONTENT = """#!/bin/sh
# D64 IRON CLAD DEFENSE (PRE-PUSH)
# Generated by Antigravity

echo "--- D64 PRE-PUSH DEFENSE CHECK ---"

# 1. Identity Lock
python tools/verify_repo_root.py
if [ $? -ne 0 ]; then
    echo "FAILED: Identity mismatch."
    exit 1
fi

# 2. Canon Hygiene
python tools/verify_canon_clean.py
if [ $? -ne 0 ]; then
    echo "FAILED: Canon is stale or dirty."
    exit 1
fi

# 3. Structure Integrity
python tools/verify_module_count.py
if [ $? -ne 0 ]; then
    echo "FAILED: System module count/structure invalid."
    exit 1
fi

echo "--- D64 DEFENSE: PASSED ---"
exit 0
"""

def install_hook():
    if not os.path.isdir(HOOK_DIR):
        print(f"ERROR: .git hooks directory not found at {HOOK_DIR}")
        print("Are you in the repo root?")
        sys.exit(1)
        
    print(f"Installing pre-push hook to {HOOK_FILE}...")
    with open(HOOK_FILE, "w") as f:
        f.write(HOOK_CONTENT)
        
    # Make executable (Windows doesn't use chmod +x exactly same way for git hooks, 
    # but git bash/cygwin/msysgit usually respects content if it's sh)
    # On Windows native, pre-push without extension might be tricky if not running from bash, 
    # but let's assume standard Git for Windows environment.
    
    print("Hook installed successfully.")

if __name__ == "__main__":
    install_hook()
